# Generated by Django 5.2.1 on 2025-06-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_conversatation_id_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
